#!/bin/bash
#SBATCH --partition=epyc2
#SBATCH --chdir=/storage/homefs/ch21o450/
#SBATCH --mail-user=chantal.hari@unibe.ch
#SBATCH --mail-type=SUBMIT,END,FAIL
#SBATCH --output=/storage/homefs/ch21o450/logs/luf_jupy_%j.out
#SBATCH --error=/storage/homefs/ch21o450/logs/luf_jupy_%j.err
#SBATCH --time=24:00:00
#SBATCH --cpus-per-task=10
#SBATCH --mem=10G

module load Anaconda3

chmod +x /storage/homefs/ch21o450/scripts/BioScenComb/landuse_filter.ipynb 

# Pass the arguments to luf.py
15051 jupyter-compute /storage/homefs/ch21o450/scripts/BioScenComb/landuse_filter.ipynb 
