#!/bin/bash
#SBATCH --partition=epyc2
#SBATCH --chdir=/storage/homefs/ch21o450/
#SBATCH --mail-user=chantal.hari@unibe.ch
#SBATCH --mail-type=SUBMIT,END,FAIL
#SBATCH --output=/storage/homefs/ch21o450/logs/luf_%j.out
#SBATCH --error=/storage/homefs/ch21o450/logs/luf_%j.err
#SBATCH --time=24:00:00
#SBATCH --cpus-per-task=10
#SBATCH --mem=10G

module load Anaconda3

# Define arrays of taxas, models and times
TAXAS=("Amphibians" "Reptiles" "Mammals")
MODELS=("GAM" "GBM")
TIME=(35 65 85)

# Loop over taxas
for taxa in "${TAXAS[@]}"
do
    # Loop over models
    for model in "${MODELS[@]}"
    do
        # Loop over times
        for time in "${TIME[@]}"
        do
            # Pass the arguments to luf.py
            python3 /storage/homefs/ch21o450/scripts/BioScenComb/luf.py -t "$time" -m "$model" -a "$taxa"
        done
    done
done
