#!/bin/bash
#SBATCH --partition=epyc2
#SBATCH --chdir=/storage/homefs/ch21o450/
#SBATCH --mail-user=chantal.hari@unibe.ch
#SBATCH --mail-type=SUBMIT,END,FAIL
#SBATCH --output=/storage/homefs/ch21o450/logs/luf_%j.out
#SBATCH --error=/storage/homefs/ch21o450/logs/luf_%j.err
#SBATCH --time=24:00:00
#SBATCH --cpus-per-task=10
#SBATCH --mem=10G

module load Anaconda3

# Define arrays of taxas and models
TAXAS=("Amphibians" "Reptiles" "Mammals")
MODELS=("GAM" "GBM")
TIME=(35 65 85)

TIME=${TIME[$SLURM_ARRAY_TASK_ID]}
TAXA=${TAXAS[$SLURM_ARRAY_TASK_ID]}
MODEL=${MODELS[$SLURM_ARRAY_TASK_ID]}

# Pass the arguments to luf.py
srun -B /storage python3 /storage/homefs/ch21o450/scripts/BioScenComb/luf.py -t $TIME -m $MODEL -a $TAXA
