#!/bin/bash
#SBATCH --partition=epyc2
#SBATCH --chdir=/storage/homefs/ch21o450/
#SBATCH --mail-user=chantal.hari@unibe.ch
#SBATCH --mail-type=SUBMIT,END,FAIL
#SBATCH --output=/storage/homefs/ch21o450/logs/luf_birds%A_%a.out
#SBATCH --error=/storage/homefs/ch21o450/logs/luf_birds%A_%a.err
#SBATCH --time=239:59:00
#SBATCH --cpus-per-task=10
#SBATCH --mem=100G

module load Anaconda3

# Define arrays of time and models
MODELS=("GAM")
TIME=(35 65 85)

# Calculate values of TIME and MODEL based on SLURM_ARRAY_TASK_ID
TIME=${TIME[$SLURM_ARRAY_TASK_ID % ${#TIME[@]}]}
MODEL=${MODELS[$SLURM_ARRAY_TASK_ID / ${#TIME[@]}]}

chmod +x /storage/homefs/ch21o450/scripts/BioScenComb/functions/luf_birds.py

# Pass the arguments to luf.py
python3 /storage/homefs/ch21o450/scripts/BioScenComb/functions/luf_birds.py -t $TIME -m $MODEL
