#!/bin/bash

#SBATCH --p=epyc2
#SBATCH --chdir=/storage/homefs/ch21o450/
#SBATCH --mail-user=chantal.hari@unibe.ch
#SBATCH --mail-type==SUBMIT,END,FAIL
#SBATCH -o logs/calc_pa%j.out
#SBATCH -e logs/calc_pa%j.err
#SBATCH --ntasks=1
#SBATCH --mem=50G
#SBATCH --cpus-per-task=64
#SBATCH --time=00:01:00
#SBATCH --output=/home/harichan/logs/calc_pa_%A_%a.out

R --vanilla -f /storage/homefs/ch21o450/scripts/project-1/functions/01_Calc_PA.R $SLURM_ARRAY_TASK_ID
