#!/bin/bash

#SBATCH --partition=epyc2
#SBATCH --chdir=/storage/homefs/ch21o450/
#SBATCH --mail-user=chantal.hari@unibe.ch
#SBATCH --mail-type==SUBMIT,END,FAIL
#SBATCH --output=/storage/homefs/ch21o450/logs/calc_pa%j.out
#SBATCH --error=/storage/homefs/ch21o450/logs/calc_pa%j.err
#SBATCH --time=00:01:00
#SBATCH --output=//storage/homefs/ch21o450/logs/calc_pa_%A_%a.out
#SBATCH --mem=10G

module load R/4.1.0-foss-2021a

R --vanilla -f /storage/homefs/ch21o450/scripts/project-1/functions/01_Calc_PA.R --args $SLURM_ARRAY_TASK_ID
